[package]
name = "zk-paillier"
version = "0.1.0"
authors = [
    "Gary <gary@kzencorp.com>",
    "Morten Dahl <mortendahlcs@gmail.com>",
    "Omer <omer.shlomovits@gmail.com>"
]
keywords = ["paillier", "zero knowledge"]


license = "GPL-3.0-or-later"
categories = ["cryptography"]

[lib]
crate-type = ["lib"]

[dependencies]
paillier = { git = "https://github.com/KZen-networks/rust-paillier", branch = "feature/libra-support-fix" }
ring = "0.14"
rand = "0.5"
rayon = "1.0"
bit-vec = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.curv]
git = "https://github.com/KZen-networks/curv"
branch = "feature/libra-support-fix"

[patch.crates-io]
rust-gmp = { version = "0.5.0", features = ["serde_support"], git = "https://github.com/KZen-networks/rust-gmp" }

[dev-dependencies]
criterion = "0.2"


